name: Build and Publish Binaries

on:
  release:
    types:
      - created

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1

    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - uses: Swatinem/rust-cache@v1

#      - name: Check version
#        working-directory: ./package-publisher
#        run: |
#          cargo build
#          ./target/debug/exogress-package-publisher --version ${{ github.event.release.tag_name }} check_version

  build-and-publish:
    needs: verify
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            upload_asset_name: libexogress-macos-x86_64
            rustflags: ''
          - os: macos-latest
            target: aarch64-apple-darwin
            upload_asset_name: libexogress-macos-aarch64
            rustflags: ''
          - os: windows-latest
            upload_asset_name: libexogress-win32
            target: i686-pc-windows-msvc
            rustflags: '-C target-feature=-crt-static'
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            upload_asset_name: libexogress-win64
            rustflags: '-C target-feature=-crt-static'
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            upload_asset_name: libexogress-aarch64
            rustflags: '-C target-feature=-crt-static'
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            upload_asset_name: libexogress-linux-aarch64-gnu
            rustflags: ''
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            upload_asset_name: libexogress-linux-aarch64-musl
            rustflags: '-C target-feature=-crt-static'
          - os: ubuntu-latest
            target: arm-unknown-linux-gnueabi
            upload_asset_name: libexogress-linux-arm-gnueabi
            rustflags: ''
          - os: ubuntu-latest
            target: arm-unknown-linux-musleabi
            upload_asset_name: libexogress-linux-arm-musleabi
            rustflags: '-C target-feature=-crt-static'
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            upload_asset_name: libexogress-linux-armv7-gnueabihf
            rustflags: ''
          - os: ubuntu-latest
            target: armv7-unknown-linux-musleabihf
            upload_asset_name: libexogress-linux-armv7-musleabihf
            rustflags: '-C target-feature=-crt-static'
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            upload_asset_name: libexogress-linux-x86_64-gnu
            rustflags: ''
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            upload_asset_name: libexogress-linux-x86_64-musl
            rustflags: '-C target-feature=-crt-static'

    env:
      RUST_BACKTRACE: 1

    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
        with:
          submodules: true

      - uses: Swatinem/rust-cache@v1

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
        if: matrix.target != 'aarch64-apple-darwin'

      - name: macos aarch64-specific items
        run: |
          # Use nightly for now
          rustup toolchain install --profile=minimal nightly
          rustup default nightly

          # Use the beta compiler
          sudo xcode-select -s /Applications/Xcode_12.2.app/Contents/Developer/

          # Set SDK environment variables
          echo "SDKROOT=$(xcrun -sdk macosx11.0 --show-sdk-path)" >> $GITHUB_ENV
          echo "MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx11.0 --show-sdk-platform-version)" >> $GITHUB_ENV
        if: matrix.target == 'aarch64-apple-darwin'

      - name: Build release binary
        uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: ${{ matrix.rustflags }}
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}

      - name: Upload .a release binary (non-Windows)
        uses: actions/upload-release-asset@v1.0.2
        if: matrix.os != 'windows-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/${{ matrix.target }}/release/libexogress.a
          asset_name: ${{ matrix.upload_asset_name }}.a
          asset_content_type: application/octet-stream

      - name: Upload lib release binary (dylib)
        uses: actions/upload-release-asset@v1.0.2
        if: matrix.os == 'macos-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/${{ matrix.target }}/release/libexogress.dylib
          asset_name: ${{ matrix.upload_asset_name }}.dylib
          asset_content_type: application/octet-stream

      - name: Upload lib release binary (so)
        uses: actions/upload-release-asset@v1.0.2
        if: matrix.os == 'ubuntu-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/${{ matrix.target }}/release/libexogress.so
          asset_name: ${{ matrix.upload_asset_name }}.so
          asset_content_type: application/octet-stream

      - name: Upload lib release binary (Windows)
        uses: actions/upload-release-asset@v1.0.2
        if: matrix.os == 'windows-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/${{ matrix.target }}/release/exogress.lib
          asset_name: ${{ matrix.upload_asset_name }}.lib
          asset_content_type: application/octet-stream

      - name: Upload dll release binary (Windows)
        uses: actions/upload-release-asset@v1.0.2
        if: matrix.os == 'windows-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/${{ matrix.target }}/release/exogress.dll
          asset_name: ${{ matrix.upload_asset_name }}.dll
          asset_content_type: application/octet-stream

  publish-header:
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - name: Build release binary
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Upload headers
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./exogress.h
          asset_name: exogress.h
          asset_content_type: application/octet-stream

